[package]
name = "pH"
version = "0.1.0"
authors = ["Bruce Leidl <bruce@subgraph.com>"]
edition = "2018"

[dependencies]
byteorder="1.0.0"
libc = "*"
termios = "0.2.2"
lazy_static = "1.4.0"
libcitadel = { git = "https://github.com/brl/citadel-tools", rev="4ce5d439d8ec4ba7cea03e18bac208a3aff0c707" }
